# unbind default prefix and set it to ctrl-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# reload config file
bind r source-file ~/.config/tmux/tmux.conf \; display ".tmux.conf reloaded!"

# start windows and panes at 1
set -g base-index 1
setw -g pane-base-index 1

# window navigation with alt+[/] (no prefix)
bind -n M-] select-window -t :+
bind -n M-[ select-window -t :-

# set vi mode for copy mode
setw -g mode-keys vi

# do not snap to bottom after select
set -g @yank_action 'copy-pipe'

# copy mode using 'Esc'
unbind [
bind Escape copy-mode

# plugin manager
set -g @plugin 'tmux-plugins/tpm'

# sensible defaults
set -g @plugin 'tmux-plugins/tmux-sensible'

# colors
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'mocha'
set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator "  █"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_status_modules "directory session date_time"
set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "yes"
set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_connect_separator "no"

# mouse
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set-option -g mouse on

# search
set -g @plugin 'tmux-plugins/tmux-copycat'

# panes
set -g @plugin 'tmux-plugins/tmux-pain-control'

# copy to clipboard
set -g @plugin 'tmux-plugins/tmux-yank'

# init tpm (keep at bottom)
run '~/.tmux/plugins/tpm/tpm'
