# unbind default prefix and set it to ctrl-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# reload config file
bind r source-file ~/.config/tmux/tmux.conf \; display ".tmux.conf reloaded!"

# start windows and panes at 1
set -g base-index 1
setw -g pane-base-index 1

# window navigation with alt+l/h (no prefix)
bind -n C-right select-window -t :+
bind -n C-left select-window -t :-

# set vi mode for copy mode
setw -g mode-keys vi

# copy mode using 'Esc'
unbind [
bind Escape copy-mode

# plugin manager
set -g @plugin 'tmux-plugins/tpm'

# sensible defaults
set -g @plugin 'tmux-plugins/tmux-sensible'

# colors
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark'

# mouse
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set-option -g mouse on

# search
set -g @plugin 'tmux-plugins/tmux-copycat'

# panes
set -g @plugin 'tmux-plugins/tmux-pain-control'

# copy to clipboard
set -g @plugin 'tmux-plugins/tmux-yank'

# init tpm (keep at bottom)
run '~/.tmux/plugins/tpm/tpm'
