#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors  true

bspc config border_width  3
bspc config window_gap    12

bspc config split_ratio	         0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# non-bspwm related

# wallpaper
feh --bg-scale ~/wallpaper.jpg

# xorg compositing
picom --daemon

# reload .Xresources
xrdb -load ~/.Xresources

# change from ugly cursor when hovering over background
xsetroot -cursor_name left_ptr
